str = "My name is Sion Jeon"
print(len(str))
print(str*10)
print(str[0])
print(str[:4])
print(str[-4:])
print(str[::-1])
print(str[1:-1])
print(str.upper())
print(str.lower())
print(str.replace('a', 'e'))